name: Build 3105 iOS IPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Print Xcode Version
      run: |
        xcodebuild -version

    - name: Build Target
      run: |
        xcodebuild build \
          -project ThreeOneOSFive.xcodeproj \
          -target 3105 \
          -configuration Release \
          -sdk iphoneos \
          SYMROOT=build \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_IDENTITY=""

    - name: Package as IPA
      run: |
        mkdir -p Payload
        cp -r build/Release-iphoneos/3105.app Payload/3105.app
        zip -r 3105_v2.2.ipa Payload

    - name: Upload Patched IPA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: 3105-v2.2-IPA
        path: 3105_v2.2.ipa
